# Site settings
title: Bitcoin Newcastle
email: your-email@yourdomain.com
description: "Bitcoin meetup in Newcastle upon Tyne, UK."
baseurl: ""
url: "http://www.bitcoinnewcastle.com"
twitter_username: BitcoinNCL
facebook_username:  BitcoinNewcastle
google_plus_url: https://plus.google.com/+bitcoinnewcastlecom/about

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
