# Site settings
title: Newcastle Bitcoin Meetup
email: bitcoinnewcastle@gmail.com
description: "Bitcoin meetup in Newcastle upon Tyne, UK."
baseurl: ""
url: "http://www.bitcoinnewcastle.com"
twitter_username: BitcoinNCL

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
